### ISSUE TITLE
Add capability to 'gcp_storage_object' to enable folder object downloads and recursive capabilities

### ISSUE THREAD

**Issue by gzimmers** [ansible-collections/google.cloud#143]
##### SUMMARY

As of right now gcp_storage_object isn't the most useful due to the lack of support regarding recursive and multi-file downloads. Instead we have to wrap gsutil rsync/cp commands with ansible shell execs.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

gcp_storage_object

##### ADDITIONAL INFORMATION

The feature would be used to recursively download folders, files, or the entirety of the buckets contents.

I'm fairly indifferent on the syntax/usage, and mainly interested in having the capability.
```yaml
- name: Download bucket contents or folder recursively
    gcp_storage_object:
      bucket: bucket-name
      action: download
      src: "*" || src: "./" || src: "." || src: "foldername" || src: "foldername/*"
      dest: "destfolder/"
      state: present
```
