### ISSUE TITLE
Add support for Cloud Deployment Manager

### ISSUE THREAD

**Issue by svpace** [ansible-collections/google.cloud#237]
##### SUMMARY
Add support for deployment manager

##### ISSUE TYPE
- Feature idea

##### ADDITIONAL INFORMATION
It would allow Ansible to leverage GCP native deployment manager to augment, complement or even as an alternative to some of the GCP modules

```yaml

- name: cloud deployment
  gcp_deployment:
    name: my-deployment
    config:
      resources:
        - name: my-vm
          type: compute.v1.instance
          properties:
            machineType: zones/us-central1-a/machineTypes/n1-standard-1
    ...
```
