### ISSUE TITLE
gcp_compute_instance always reports changed

### ISSUE THREAD

**Issue by Freyert** [ansible-collections/google.cloud#257]
##### SUMMARY
`gce_compute_instance` always returns changed.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`gce_compute_instance`

##### ANSIBLE VERSION

```paste below
$ poetry run ansible --version                                                                                  
ansible 2.9.10
  config file = None
  configured module search path = ['/Users/zzzzz/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/zzzzzz/Library/Caches/pypoetry/virtualenvs/replicaset-assertions-QUQBoPOI-py3.8/lib/python3.8/site-packages/ansible
  executable location = /Users/zzzzzz/Library/Caches/pypoetry/virtualenvs/replicaset-assertions-QUQBoPOI-py3.8/bin/ansible
  python version = 3.8.0+ (heads/3.8:694c03f, Nov 13 2019, 17:42:51) [Clang 11.0.0 (clang-1100.0.33.8)]
```

##### CONFIGURATION

```paste below

```
It's empty.

##### OS / ENVIRONMENT

OSX 10.15.5
Python 3.8.0+

##### STEPS TO REPRODUCE

```yaml
- name: Create instances
  hosts: dbservers
  gather_facts: False
  tasks:
    - name: assert instances
      delegate_to: localhost
      block:
        - name: get_host
          set_fact:
            zone: "{{ zones[(zones|length) % (inventory_hostname.split('-')[4] | int)]}}"
        - name: create data disks
          gcp_compute_disk:
            name: "{{inventory_hostname}}-storage"
            size_gb: "{{ data_disk_size }}"
            zone: "{{ zone }}"
            project: "{{ project }}"
            auth_kind: "{{ auth_kind }}"
            state: present
          register: data_disk
        - name: create instances
          register: gce_instance_vars
          gcp_compute_instance:
            name: "{{inventory_hostname}}"
            machine_type: "{{ machine_type}}"
            # deletion_protection should be set to false, otherwise even a change to the instance leads to error
            deletion_protection: false
            disks:
              - auto_delete: true
                boot: true
                initialize_params:
                  disk_size_gb: "{{boot_disk_size}}"
                  source_image: "{{ source_image }}"
              - auto_delete: false
                boot: false
                source: "{{ data_disk }}"
                device_name: storage
            labels:
              environment: "{{ project }}"
              cluster: "{{ role }}-{{ cluster }}"
            network_interfaces:
              - network:
                  selfLink: projects/ctp-playground/global/networks/default
            zone: "{{ zone }}"
            project: "{{ project }}"
            auth_kind: "{{ auth_kind }}"
            state: present
        - name: save response to file
          copy:
            dest: /tmp/{{inventory_hostname}}-b.json
            content: "{{gce_instance_vars | to_nice_json }}"
```

##### EXPECTED RESULTS

Should not be changed and the saved variable output should not have any diff.

##### ACTUAL RESULTS

The instances are always marked changed, but the variable output from the `gcp_compute_instance` does not change between runs.

```paste below

```

**Comment by Rylon** [comment]
I have this issue with `gcp_storage_bucket` also, it reports changes every time, even if nothing has changed.

**Comment by tcinbis** [comment]
I am experiencing the same behaviour when using the example provided in the ansible documentation.

Appologies for pinging @rambleraptor directly, but you seem to have done the most recent changes to [gcp_compute_instance.py](https://github.com/ansible-collections/google.cloud/blob/master/plugins/modules/gcp_compute_instance.py). 

Am I just missing something obvious here or is this behaviour expected from the module and one needs to check it manually?

Thanks!

**Comment by tcinbis** [comment]
My current workaround is to check which machines already exist using the `gcp_compute_instance_info` module.

Copied from [here](https://docs.ansible.com/ansible/latest/collections/google/cloud/gcp_compute_instance_info_module.html)
```[yml]
- name: Check for gate server running
  gcp_compute_instance_info:
    zone: "{{ GCLOUD_DEFAULT_ZONE }}"
    filters:
    - name = test-vm
    project: "{{ GCLOUD_DEFAULT_PROJECT_NAME }}"
    auth_kind: application
  register: instances
```

**Comment by Freyert** [comment]
@tcinbis and @Rylon I believe I've managed to resolve this issue by using the externally managed modules that are prefixed with `google.cloud`.

```
# requirements.yaml
---
collections:

  - name: google.cloud
    version: ">=1.0.0"
```
