### ISSUE TITLE
gcp_storage_object module changing the size of downloaded file

### ISSUE THREAD

**Issue by TejaswiniTharigopula2295** [ansible-collections/google.cloud#304]
SUMMARY
I'm using gcp_storage_object to download a exe file from gcp storage bucket. I'm able to download the file successfully but the size of the file is getting changed

ISSUE TYPE
- Bug Report

COMPONENT NAME
gcp_storage_object

ANSIBLE VERSION
 ansible 2.9

 OS / ENVIRONMENT
ubuntu 18.0

STEPS TO REPRODUCE
```
-  name: create a object
   run_once: true
   delegate_to: 127.0.0.1
   gcp_storage_object:
    action: download
    overwrite: yes
    bucket: MyBucket
    src: test.exe
    dest: "~/temp/test.exe"
    auth_kind: application
    project: xxx-xxx-xxx
    state: present
```

EXPECTED RESULTS
  Should download the required file without any change in size

ACTUAL RESULTS
  Downloaded file size is double than actual file size
