### ISSUE TITLE
Apply Resource Policy to Compute Instance

### ISSUE THREAD

**Issue by ChrisCoe** [ansible-collections/google.cloud#323]
##### SUMMARY

Hello, I hope you all are doing well. 

Ansible collection does not allow creating an instance under a resource policy. I have to use the gcloud sdk to currently bring my VMs in a COLLOCATED placement policy which a resource policy provides. Ansible can create both resource policy and instance, but no way for them to play together which breaks my heart. I don't mind installing gcloud solely to connect these components together, but a better way is this feature. Have some way to apply a resource policy to a vm instance. For example, have a field in instance module to follow a resource policy during creation.

This PR tried to complete this feature but ran into quota errors (https://github.com/ansible-collections/google.cloud/pull/194). I'm able to apply resource policies to instances while consistently avoiding the quota errors I encountered with a work around I gathered through the documentation. Seems to me like quota errors should not stop this feature request.

Thank you.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

gcp_compute_resource_policy field for google.cloud.gcp_compute_instance module.

##### ADDITIONAL INFORMATION

Forums about quota error mentioned above : 
https://groups.google.com/g/gce-discussion/c/asJA71NDkZM/m/2qon8TQZBQAJ
https://groups.google.com/g/gce-discussion/c/Lfyk38giqK8

**Comment by rambleraptor** [comment]
Hi Christian!

Thanks so much for submitting this issue. I guess I'm a little confused about the problem. It sounds like the Ansible module supports this feature, but either a quota issue on your project or potentially a GCE-wide quota issue is stopping the issue from working properly?

I'm not aware of a situation where the Ansible module could fix either of these. Both of them require manual intervention. In the case of a personal quota issue, I believe you have to file a support ticket (or talk to your org administrator) to get your quota increased. 

Do you have any more context about what you'd like the Ansible module to do in this situation?

**Comment by ChrisCoe** [comment]
Hi Alex!

Sure, I can explain better. Ansible supports creating an instance, and creating a resource policy in google cloud. Ansible does not support applying a resource policy to an instance which I find odd. That's the main problem I wish to address. My proposal for this is to create a new field to specify a resource policy when creating an instance; there are different ways to tackle the problem.

Context: I would like to have instances that are physically close to each other as mush as possible in the data center and compact placement provides this (https://cloud.google.com/compute/docs/instances/define-instance-placement). The only way to achieve this close placement is by defining a resource policy, and then having some instances follow that policy. I'm able to achieve this with some gcloud commands outside of Ansible. 

The talk about quotas was just me speculating why this may not have been done before.

**Comment by sean-freeman** [comment]
👋 Resurrecting this GH Issue, calling attention to active maintainers @toumorokoshi , @SirGitsalot , @alinabuzachis .

To re-state the problem, the REST API allows `insert` of Resource Policy/ies and subsequent `insert` of GCP CE VM instance/s with 1..n Resource Policies assigned.

See REST API documentation for GCP CE VM Instance, with top-level field `resourcePolicies[]` to provide "Resource policies applied to this instance" :
https://cloud.google.com/compute/docs/reference/rest/v1/instances/insert#body.request_body.FIELDS.resource_policy

**Summary:**

The top-level field is missing from `google.cloud.gcp_compute_instance`, and therefore Ansible cannot create GCP CE VM with ["Compact Placement Policy" or "Spread Placement Policy"](https://cloud.google.com/compute/docs/instances/placement-policies-overview).

The latter impacts SAP on GCP deployments via the [Ansible Collection `community.sap_infrastructure` from the SAP LinuxLab Open-Source Initiative](https://github.com/sap-linuxlab/community.sap_infrastructure), which provides equalised deployments of SAP Software Scenarios across multiple Infrastructure Platforms.

Ansible Collection functionality to "Provision VM with a Spread Placement" is provided by all other Cloud IaaS vendors.

Bluntly speaking, this is a 1 field (type: list) append to the Ansible Module's Python code. It's an easy fix that should have been delivered 4 years ago when it was initially raised.

**Comment by toumorokoshi** [comment]
> 👋 Resurrecting this GH Issue, calling attention to active maintainers @toumorokoshi

Unfortunately I'm no longer a maintainer - I left Google a little while back. But @SirGitsalot should be able to help!

**Comment by sean-freeman** [comment]
@SirGitsalot Can you please investigate this 2 line change impacting Instance?

From what I can see, the only changes required are:

```python
DOCUMENTATION = '''
---
module: gcp_compute_instance
  ....
  resource_policies:
    description:
    - The list of resource policies applied to this instance.
    elements: str
    required: false
    type: list
  ....
```

```python
def main():
    module = GcpModule(
        argument_spec=dict(
            ....
            resource_policies=dict(type='list', elements='str'),
            ....
```
```python
def resource_to_request(module):
    request = {
        ....
        u'resourcePolicies': module.params.get('resource_policies'),
        ....
```


### Playbook test example:

```yaml
- name: Create Placement Policies when High Availability
  register: gcp_resource_policy
  run_once: true
  google.cloud.gcp_compute_resource_policy:
    project: "{{ gcp_project }}"
    region: "{{ gcp_region }}"
    name: "{{ gcp_placement_resource_name }}"
    description: "Spread Placement Policy"
    # VM instances (HA Pairs) spread across up to 3 Availability Domains (different racks)
    group_placement_policy:
      availability_domain_count: 3 # Set Placement Policy to Spread
      # collocation: COLLOCATED    # Set Placement Policy to Collocated, not used
      # vm_count: 0  # Use when bulk-create of VMs, not used
    auth_kind: "serviceaccount"
    service_account_file: "{{ gcp_credentials_json }}"


- name: Provision Google Cloud VM
  google.cloud.gcp_compute_instance:
    state: present
    project: "{{ gcp_project }}"
    zone: "{{ gcp_region_zone }}"
    name: ""
    machine_type: ""

    resource_policies: [ "{{ gcp_placement_resource_name}}" ]

    network_interfaces:
      - network:
          selfLink: "{{ __task_gcp_vpc_info.resources[0].selfLink }}"
        subnetwork:
          selfLink: "{{ __task_gcp_vpc_subnet_info.resources[0].selfLink }}"

    metadata:
      enable-oslogin: false # Do not use GCP Project OS Login approach for SSH Keys
      block-project-ssh-keys: true # Do not use GCP Project Metadata approach for SSH Keys
      ssh-keys: "admin:{{ lookup('ansible.builtin.file', ssh_host_public_key_file_path ) }}" # Uses the GCP VM Instance Metadata approach for SSH Keys. Shows in GCP Console GUI under 'SSH Keys' for the VM Instance. Can not use 'root' because SSH 'PermitRootLogin' by default is 'no'.

    service_accounts: # List of service accounts authorized for Google Cloud VM (allow access via Instance Metadata service to computeMetadata/v1/instance/service-accounts etc for fence_gce Fencing Agent)
      - email: "" # Empty string for service account name, will default to the "Compute Engine Default Service Account" for the GCP Project (e.g. xx-compute@developer.gserviceaccount.com)
        scopes:
          - "https://www.googleapis.com/auth/cloud-platform" # Allow full access to all Cloud APIs

    auth_kind: "serviceaccount"
    service_account_file: "{{ gcp_credentials_json }}"
```
