### ISSUE TITLE
"Required field ''resource.fingerprint'' not specified" when gcp_compute_backend_service is used on existing backend (breaking idempotency)

### ISSUE THREAD

**Issue by gavenkoa** [ansible-collections/google.cloud#342]
First time execution of following succeeds:

```
  - name: Create a backend service
    google.cloud.gcp_compute_backend_service:
      project: "{{ gcp_project }}"
      auth_kind: serviceaccount
      service_account_file: "{{ gcp_secret }}"
      name: "{{ gcp_env }}-admin-backend-service"
      backends:
      - group: "{{ gcpRspAdminInstanceGroup.selfLink }}"
        # To avoid: [WARNING]: The value 1.0 (type float) in a string field was converted to '1.0' (type string).
        capacity_scaler: "1.0"
        # To avoid: [WARNING]: The value 0.8 (type float) in a string field was converted to '0.8' (type string).
        max_utilization: "0.8"
      health_checks:
      - "https://www.googleapis.com/compute/v1/projects/{{ gcp_project }}/global/healthChecks/admin-health-check"
      protocol: HTTPS
      port_name: server-admin
      security_policy: null
      enable_cdn: 'false'
      state: present
```

but if resource is already here above code fails:

```
The full traceback is:
  File "/tmp/ansible_google.cloud.gcp_compute_backend_service_payload_4m7preqj/ansible_google.cloud.gcp_compute_backend_service_payload.zip/ansible_collections/google/cloud/plugins/module_utils/gcp_utils.py", line 312, in raise_for_status
    response.raise_for_status()
  File "/usr/lib/python3.6/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
fatal: [localhost]: FAILED! => changed=false
  invocation:
    module_args:
      affinity_cookie_ttl_sec: null
      auth_kind: serviceaccount
      backends:
      - balancing_mode: UTILIZATION
        capacity_scaler: '1.0'
        description: null
        group: https://www.googleapis.com/compute/v1/projects/project-XXX/zones/europe-west1-b/instanceGroups/stage-admin-group
        max_connections: null
        max_connections_per_endpoint: null
        max_connections_per_instance: null
        max_rate: null
        max_rate_per_endpoint: null
        max_rate_per_instance: null
        max_utilization: '0.8'
      cdn_policy: null
      circuit_breakers: null
      connection_draining: null
      consistent_hash: null
      custom_request_headers: null
      description: null
      enable_cdn: false
      env_type: null
      health_checks:
      - https://www.googleapis.com/compute/v1/projects/project-XXX/global/healthChecks/admin-health-check
      iap: null
      load_balancing_scheme: EXTERNAL
      locality_lb_policy: null
      log_config: null
      name: stage-admin-backend-service
      outlier_detection: null
      port_name: server-admin
      project: project-XXX
      protocol: HTTPS
      scopes:
      - https://www.googleapis.com/auth/compute
      security_policy: null
      service_account_contents: null
      service_account_email: null
      service_account_file: files/secret.json
      session_affinity: null
      state: present
      timeout_sec: null
  msg: 'GCP returned error: {''error'': {''code'': 400, ''message'': "Required field ''resource.fingerprint'' not specified", ''errors'': [{''message'': "Required field ''resource.fingerprint'' not specified", ''domain'': ''global'', ''reason'': ''required''}]}}'
```

After removal of the resource with `state: absent` first run `state: present` succeeds but for all other subsequent calls with `state: present`  problem reappears.

That makes task **non-idempotent**.

Reproduced with:

* Ansible 2.9 + built-in modules
* Ansible 2.9 + collection v1.0.1
