### ISSUE TITLE
Manually specifying a subnetwork for google.cloud.gcp_compute_instance

### ISSUE THREAD

**Issue by Freyert** [ansible-collections/google.cloud#358]
##### SUMMARY
It's not clear how to specify a `subnetwork` for a `network_interfaces` element on a `google.cloud.gcp_compute_instance` no matter what I try the API request is made without a `network_interface` if I try to manually specify a `subnetwork` as per the documentation.

```json
{"changed": false, "msg": "GCP returned error: {'error': {'errors': [{'domain': 'global', 'reason': 'invalid', 'message': \"Invalid value for field 'resource.networkInterfaces': ''. At least one network interface is required.\"}], 'code': 400, 'message': \"Invalid value for field 'resource.networkInterfaces': ''. At least one network interface is required.\"}}"}
```

Here is my attempt:
https://stackoverflow.com/questions/65582174/specifying-a-subnetwork-for-ansible-google-cloud-compute-instance

```yaml
- name: create a instance
  google.cloud.gcp_compute_instance:
    name: test_object
    machine_type: n1-standard-1
    disks:
    - auto_delete: 'true'
      boot: 'true'
      source: "{{ disk }}"
    - auto_delete: 'true'
      interface: NVME
      type: SCRATCH
      initialize_params:
        disk_type: local-ssd
    labels:
      environment: production
    network_interfaces:   # <<< does not work. API request is made without a network_interface
    - network:
       selfLink: "https://blah/blah/blah/networkY"
      subnetwork:
       selfLink: "https://blah/blah/blah/subnetworkX"
    zone: us-central1-a
    project: test_project
    auth_kind: serviceaccount
    service_account_file: "/tmp/auth.pem"
    state: present
```

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

https://github.com/ansible-collections/google.cloud/blob/master/plugins/modules/gcp_compute_instance.py
##### ANSIBLE VERSION

```paste below
$ ansible --version
ansible 2.9.15
  config file = None
  configured module search path = ['/Users/xxxxx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.9.15/libexec/lib/python3.9/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.9.0 (default, Oct 27 2020, 14:15:17) [Clang 12.0.0 (clang-1200.0.32.21)]
```
