### ISSUE TITLE
GCP Ansible Collection plugin(s) should support tunneling through IAP

### ISSUE THREAD

**Issue by vanguard737** [ansible-collections/google.cloud#373]
##### SUMMARY
If you have a target Compute instance running in an IAP-protected private network, and an Ansible controller machine running outside that network, you cannot use Ansible to manage that target instance via the dynamic inventory plugin.  

Even though the controller can connect to the target via `gcloud compute ssh ... --tunnel-through-iap`, and the [GCP inventory plugin](https://github.com/ansible-collections/google.cloud/blob/master/plugins/inventory/gcp_compute.py) is configured correctly, IAP prevents Ansible from talking to the target.  

The GCP Ansible Collection should provide a way around this.  AFAICT, currently, it does not.

My best guess is that this will require a [Connection plugin](https://docs.ansible.com/ansible/latest/plugins/connection.html), though that is speculative.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
`plugins/inventory/gcp_compute.py` (relevant)  
`plugins/connection/gcp_iap.py` (new, if needed?)

##### ADDITIONAL INFORMATION
Assume the following, for convenience:  
- Ansible controller machine, Ubuntu 18.04, running outside of any GCP network, with `gcloud` set up and appropriate credentials.  
- Target machine, Ubuntu 20.04, running within a GCP IAP-protected network (such that the firewall only permits ingress to tcp:22 from the standard IAP range, 35.235.240.0/20).  
- The controller machine attempts to locate the target machine via the GCP inventory plugin (`plugins/inventory/gcp_compute.py`), and execute a trivial Ansible playbook.
	
Currently, considered unto itself, the GCP inventory plugin works more-or-less as expected.  It will accurately gather information about the target machine, returning the appropriate private IP address (or public IP, depending on your configuration).  

However, Ansible then immediately fails when executing the playbook.  Ansible works by issuing SSH commands - it has no way of knowing that it needs to use `gcloud compute ssh ... --tunnel-through-iap` instead.  So, because port 22 on the target VM is only accessible through IAP, the Ansible play fails.

Also relevant:  https://github.com/ansible/ansible/issues/66310.  
- That ticket was filed on GitHub in 2020, while the relevant code was still owned by Ansible.  However, in eight months, [no tagged human being or organization](https://github.com/ansible/ansible/issues/66310#issuecomment-572708910) ever addressed the matter.  Ansible's GitHub robot auto-closed the issue in [August 2020](https://github.com/ansible/ansible/issues/66310#issuecomment-674420912), when this code was migrated to the [GCP Ansible Collection](https://galaxy.ansible.com/google/cloud).
- That ticket accurately summarizes the problem, as well as the problems with some possible workarounds.  Speaking of which...  
- Workarounds (mentioned both here, and on StackExchange, and as Github gists, and the ansible-project Google group) include: Fragile and messy bash wrappers; cumbersome, dedicated bastion VMs;  ditching IAP altogether in favor of a traditional VPN; and other ideas that seemed even weirder and worse.  Seems like the best thing for the GCP/Ansible community overall is a centralized solution via the GCP Ansible Collection.  
- Lastly, this ticket was filed against the [GCP Inventory plugin](https://github.com/ansible-collections/google.cloud/blob/master/plugins/inventory/gcp_compute.py).  But:  Is that right?

That is:  Is the Inventory plugin the issue?  Or does this problem call for a [Connection plugin](https://docs.ansible.com/ansible/latest/plugins/connection.html)?  The Inventory plugin does seem to provide accurate info about the target machine - there's just no way for Ansible to pass that info through `gcloud compute ssh` and IAP.  FWIW, Connection plugins do seem to be the preferred means for Ansible to handle non-SSH connection methods (e.g. [Docker](https://github.com/ansible-collections/community.docker/tree/main/plugins/connection) and [AWS SSM](https://github.com/ansible-collections/community.aws/blob/main/plugins/connection/aws_ssm.py)).  At this point, though, my conclusions are - er - tentative at best.  

See below for a sanitized version of our current GCP dynamic inventory file - which seems like it should work, but does not.  

Happy to provide further info as needed.  

```
---
# Dynamic inventory file example
# https://docs.ansible.com/ansible/latest/collections/google/cloud/gcp_compute_inventory.html
plugin: google.cloud.gcp_compute
projects:
    - project_name
auth_kind: serviceaccount
service_account_file: /path/to/serviceaccount.json
keyed_groups:
    # Create groups from GCE labels
    - prefix: gcp
      key: labels
hostnames:
    # List host by name, instead of the default public ip
    - name
compose:
    # Set an inventory parameter to use the Public IP address to connect to the host
    # If you have a public IP, use "networkInterfaces[0].accessConfigs[0].natIP".
    # But in this scenario, you may only have a private IP, so instead use:
    ansible_host: networkInterfaces[0].networkIP

```
