### ISSUE TITLE
Autopilot

### ISSUE THREAD

**Issue by jobcespedes** [ansible-collections/google.cloud#386]
##### SUMMARY

Support autopilot clusters

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

Google Kubernetes Engine Cluster

##### ADDITIONAL INFORMATION

Allow creation of an autopilot GKE cluster

```yaml
- name: create a cluster
  google.cloud.gcp_container_cluster:
    name: my-cluster
    initial_node_count: 2
    master_auth:
      username: cluster_admin
      password: my-secret-password
    autopilot: true
    location: us-central1-a
    project: test_project
    auth_kind: serviceaccount
    service_account_file: "/tmp/auth.pem"
    state: present
```
