### ISSUE TITLE
Ability to run VMs in GCE without an external IP

### ISSUE THREAD

**Issue by emanueleleopardi** [ansible-collections/google.cloud#394]
##### SUMMARY

Hello,
 I tried to run a GCE instance without the need for an external IP but I couldn't really find a way to achieve this, could you shed some light? Is this supported atm?

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

google.cloud.gcp_compute_instance
##### ADDITIONAL INFORMATION

```yaml
- name: Create Instance
  google.cloud.gcp_compute_instance:
< .... >
        access_configs:
          - name: External NAT
            nat_ip: "{{ address }}"
            type: ONE_TO_ONE_NAT
< ... >
    zone: "{{ zone }}"
    project: "{{ lookup('env', 'GCE_PROJECT_ID') }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ lookup('env', 'GCP_SA_KEY') | default(json_key, true) }}"
```
