### ISSUE TITLE
Add support for confidential compute instances

### ISSUE THREAD

**Issue by theCalcaholic** [ansible-collections/google.cloud#400]
##### SUMMARY

While being added to terraform some time ago, the google.cloud ansible collection is still lacking support for the compute instance feature 'confidential compute' (i.e. RAM encryption).
Since this requires only adding a single boolean to the instance config, it should be fairly easy to implement

##### ISSUE TYPE
- upstream feature parity

##### COMPONENT NAME

google_compute_instance

```yaml
# Minimal example of instance creation with confidential compute enabled:
- name: "Create confidential compute instance"
  gcp_compute_instance: &compute_instance_defaults
    name: "confidential-instance"
    machine_type: "n2d-standard-n2" # Must match n2d-.*
    disks:
      - boot: true
        source: "{{ some-disk }}" # Disk type must be pd-ssd
    auth_kind: "application"
    state: present
    confidential_instance_config:
      enable_confidential_compute: "{{ enable_confidential_compute }}"
```
