### ISSUE TITLE
filters not working

### ISSUE THREAD

**Issue by xifanyan** [ansible-collections/google.cloud#421]
##### SUMMARY

I am trying to specify filters following example of online docs to pull only the active nodes,
filters:
  - metadata.drtype = active
but it throw an exception on not able to recoganize the field
 
then I switched to
  - machineType = n1-standard-32
 This time, it runs but without any result.

if I leave filters with default e.g., filters: [], I was able to ansible-investory -i xxxxx.gcp.yml --list and see all the nodes and fields.

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
ansible 2.10.8
  config file = /usr/local/xxxxxxx/home/xxxxxx/.ansible.cfg
  configured module search path = ['/usr/local/xxxxxxx/home/xxxxxxx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml
plugin: gcp_compute
projects:
  - xxxxx-dev1

cache: false
cache_plugin: jsonfile
cache_connection: /tmp/xxxxx-nonprod-cache

filters: 
  - metadata.drtype = active

auth_kind: application
hostnames:
  - name
keyed_groups:
  - prefix: tag
    key: tags['items']
```

##### ACTUAL RESULTS

```paste below
[WARNING]:  * Failed to parse /usr/local/xxxxxxx/home/xxxxxxxx/ansible_win_ssh/inventory/nonprod.gcp.yml with auto plugin: [{'message': "Invalid value for field 'filter':
'metadata.drtype = active'. Invalid list filter expression.", 'domain': 'global', 'reason': 'invalid'}]
```
