### ISSUE TITLE
Action to attach and detach persistent disks to running GCE instance

### ISSUE THREAD

**Issue by TinLe** [ansible-collections/google.cloud#462]
##### SUMMARY

Please add support for attach/detach persistent disk from running GCE instance.  A related bug is discussed in issue https://github.com/ansible-collections/google.cloud/issues/193

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

google.cloud.gcp_compute_instance would be a good place to add the attach/detach actions.

##### ADDITIONAL INFORMATION

It would be nice to be able to detach a persistent disk from one running instance and attach it to another running instance.  This is good for doing DR testing use case.

```yaml
   - name: detach persistent disk
     gcp_compute_instance:
         name: test-vm
         disks:
           - detach: true
             source: "{{ disk }}"
```

```yaml
   - name: attach persistent disk
     gcp_compute_instance:
         name: restore-test-vm
         disks:
           - attach: true
             source: "{{ disk }}"
```
