### ISSUE TITLE
Add support for google cloud cloudarmor security policies configuration

### ISSUE THREAD

**Issue by nkichukov** [ansible-collections/google.cloud#467]
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
Google supports configuring cloud armor rules. However, ansible does not yet have a module to do so.

##### ADDITIONAL INFORMATION
This feature will allow ansible to provision cloud armor security policies in GCP and link those to backends.

```yaml
description: my description
fingerprint: PWfLGDWQDLY=
id: '123'
name: my-policy
rules:
- action: allow
  description: default rule
  match:
      config:
        srcIpRanges:
        - '*'
      versionedExpr: SRC_IPS_V1
    preview: false
    priority: 2147483647
  selfLink: https://www.googleapis.com/compute/v1/projects/my-project/global/securityPolicies/my-policy
```
For more information, please refer to:
https://cloud.google.com/armor/docs/configure-security-policies
