### ISSUE TITLE
use of network_config.default_snat_status causes 'Invalid value at cluster.network_config.default_snat_status' Error

### ISSUE THREAD

**Issue by hectoralicea** [ansible-collections/google.cloud#496]
##### SUMMARY

Use of network_config.default_snat_status causes 'Invalid value at cluster.network_config.default_snat_status' Error

Without this option there is no way to create a cluster with the equivalent of the `gcloud container clusters` flag `--disable-default-snat`

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

google.cloud.gcp_container_cluster

##### ANSIBLE VERSION

```paste below
ansible 2.10.15
  config file = /Users/ha85006/gitrepos/gcp/ansible-playbooks/ansible-role-gcp-gke/tests/ansible.cfg
  configured module search path = ['/Users/ha85006/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/ha85006/Library/Python/3.9/lib/python/site-packages/ansible
  executable location = /Users/ha85006/Library/Python/3.9/bin/ansible
  python version = 3.9.4 (default, Apr  5 2021, 01:49:30) [Clang 12.0.0 (clang-1200.0.32.29)]
```

##### COLLECTION VERSION

```paste below
google.cloud      1.0.2 
```

##### CONFIGURATION

```paste below
ha85006$ ansible-config dump --only-changed
DEFAULT_HOST_LIST(/Users/ha85006/gitrepos/gcp/ansible-playbooks/ansible-role-gcp-gke/tests/ansible.cfg) = ['/Users/ha85006/gitrepos/gcp/ansible-playbooks/ansible-role-gcp
DEFAULT_ROLES_PATH(/Users/ha85006/gitrepos/gcp/ansible-playbooks/ansible-role-gcp-gke/tests/ansible.cfg) = ['/Users/ha85006/gitrepos/gcp/ansible-playbooks']
DEFAULT_STDOUT_CALLBACK(/Users/ha85006/gitrepos/gcp/ansible-playbooks/ansible-role-gcp-gke/tests/ansible.cfg) = yaml
HOST_KEY_CHECKING(env: ANSIBLE_HOST_KEY_CHECKING) = False
```

##### OS / ENVIRONMENT

Running on MacOS Big Sur

##### STEPS TO REPRODUCE

```yaml
- name: create a cluster
  google.cloud.gcp_container_cluster:
    name: '{{ k8s_cluster_name }}'
    initial_node_count: '{{ k8s_desired_number_of_nodes }}'
    network: '{{ gcp_vpc_network }}'
    subnetwork: '{{ gcp_vpc_subnetwork }}'
    network_config:
      default_snat_status: no
    private_cluster_config:
      enable_private_endpoint: yes
      enable_private_nodes: yes
      master_ipv4_cidr_block: '{{ gcp_gke_master_ipv4_cidr_block }}'
    ip_allocation_policy:
      subnetwork_name: '{{ gcp_vpc_subnetwork_name }}'
      cluster_secondary_range_name: '{{ gcp_gke_cluster_secondary_range_name }}'
      services_secondary_range_name: '{{ gcp_gke_services_secondary_range_name }}'
      use_ip_aliases: yes
    master_authorized_networks_config:
      enabled: yes
      cidr_blocks: '{{ gcp_gke_master_authorized_networks_config }}'
    default_max_pods_constraint:
      max_pods_per_node: '{{ gcp_gke_max_pods_per_node }}'      
    zone: '{{ gcp_region }}'
    project: '{{ gcp_project_id }}'
    node_config:
      machine_type:  "{{ machine_type }}"
      disk_size_gb: "{{ disk_size_gb }}"
      service_account: '{{ compute_engine_default_service_account }}'
    state: present
  register: cluster
```

##### ACTUAL RESULTS

```paste below
TASK [ansible-role-gcp-gke : create a cluster] ***************************************************************************************************************************
fatal: [172.25.126.40]: FAILED! => changed=false 
  msg: 'GCP returned error: {''error'': {''code'': 400, ''message'': "Invalid value at ''cluster.network_config.default_snat_status'' (type.googleapis.com/google.container.v1.DefaultSnatStatus), false", ''status'': ''INVALID_ARGUMENT'', ''details'': [{''@type'': ''type.googleapis.com/google.rpc.BadRequest'', ''fieldViolations'': [{''field'': ''cluster.network_config.default_snat_status'', ''description'': "Invalid value at ''cluster.network_config.default_snat_status'' (type.googleapis.com/google.container.v1.DefaultSnatStatus), false"}]}]}}'

```
