### ISSUE TITLE
Support for Google Secret Manager resources

### ISSUE THREAD

**Issue by Ameausoone** [ansible-collections/google.cloud#543]
##### SUMMARY

It will be handy to could create Google secret with Ansible Google cloud collection

##### ISSUE TYPE
- Create Google secret manager
- Create Google secret manager version

##### COMPONENT NAME
- gcp_secret_manager

##### ADDITIONAL INFORMATION

gcloud secrets create {{ secret_name }} --replication-policy=automatic --project={{ gcp_project }} --labels='created_by=ansible'

```yaml
- name: Create a Google Secret manager
  google.cloud.gcp_secret_manager:
    name: test-secret
    project: test_project
    auth_kind: serviceaccount
    service_account_file: "/tmp/auth.pem"
    state: present
    replication_policy: automatic
    content: "test"
```
