### ISSUE TITLE
gcp_compute_instance_facts problem with the "~" operator

### ISSUE THREAD

**Issue by barbacbd** [ansible-collections/google.cloud#549]
When I try to use the "contains" operator or "~" the playbook will fail with something similar to:

"Invalid value for field 'filter': 'name ~ whatever-I-name-it

When I run the (assumed) same/similar command with gcloud it will work,

gcloud compute instances list --filter="name~whatever-I-name-it"

The [ansible docs](https://docs.ansible.com/ansible/latest/collections/google/cloud/gcp_compute_instance_info_module.html) state that the gcp filters will work followed by that [link](https://cloud.google.com/sdk/gcloud/reference/topic/filters).

I noticed an older issue https://github.com/ansible/ansible/issues/48824 from a couple of years ago where it was determined that only '=', '<', and '>' were able to be used. Has there been any support to add other operators, if not could the docs be changed to reflect?

##### COLLECTION VERSION

```
Collection   Version
------------ -------
google.cloud 1.1.2


ansible [core 2.14.1]
```

##### OS / ENVIRONMENT

Using RHEL 8.x

##### STEPS TO REPRODUCE

```yaml
- name: Retrieve platform instance list
  google.cloud.gcp_compute_instance_info:
    auth_kind: "serviceaccount"
    filters:
    - name \~ "{{ gcp_instance_pattern }}"
    zone: "{{ gcp_zone }}"
    project: "{{ gcp_project }}"
    service_account_file: "{{ gcp_service_account_file }}"
  register: gcp_machines
  run_once: true
```
The gcp_instance_pattern is a string `whatever-I-name-it`

##### EXPECTED RESULTS

A list of gcp instances where the names contain the search string are found are returned. 

##### ACTUAL RESULTS

`"Invalid value for field 'filter': 'name ~ whatever-I-name-it ...`

```paste below
"Invalid value for field 'filter': 'name ~ whatever-I-name-it ...
```
