### ISSUE TITLE
gcp_compute_node_group examples use a "region" key that is not documented

### ISSUE THREAD

**Issue by goneri** [ansible-collections/google.cloud#552]
##### SUMMARY

`gcp_compute_node_group` EXAMPLES block comes with an example that use the `region` key. However, the module options doesn't document the key.

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

gcp_compute_node_group and maybe more.

**Comment by toumorokoshi** [comment]
I took a look, and the example looks be accurate as `region` pertains to the node *template*, not the group:

```
- name: create a node template
  google.cloud.gcp_compute_node_template:
    name: "{{ resource_name }}"
    region: us-central1
    node_type: n1-node-96-624
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: present
  register: node_template

- name: create a node group
  google.cloud.gcp_compute_node_group:
    name: test_object
    zone: us-central1-a
    description: example group for ansible
    size: 1
    node_template: "{{ node_template }}"
    project: test_project
    auth_kind: serviceaccount
    service_account_file: "/tmp/auth.pem"
    state: present
```

node groups are zonal.  If I missed the place where a region is passed for a node group, can you provide a link to the example?
