### ISSUE TITLE
Add support for info module to describe GCP Secret Manager - List secrets and versions metadata

### ISSUE THREAD

**Issue by tze-dev** [ansible-collections/google.cloud#579]
##### SUMMARY

Add support for info module to describe GCP Secret Manager to list secrets and versions metadata

**NOTE**: The intention is not to list the secret payloads - it is only for listing metadata.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

module: `gcp_secretmanager_info`

##### ADDITIONAL INFORMATION

This info module can be used to obtain a list of secrets and the associated versions metadata in a GCP Project.

```yaml
- hosts: localhost
  vars:
     project_number: 111111111111
     auth_kind: application
  tasks:
    - name: List secrets info
      gcp_secretmanager_info:
         project: '{{ project_id }}'
         auth_kind: '{{ auth_kind }}'
      register: reg_secrets_info

    - name: Print secrets metadata
      debug:
        var: reg_secrets_info
```
