### ISSUE TITLE
google.cloud.gcp_bigquery_table: Bigquery table with clustering creation returns error

### ISSUE THREAD

**Issue by sydro** [ansible-collections/google.cloud#620]
##### SUMMARY
Bigquery table with clustering creation returns error

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
google.cloud.gcp_bigquery_table

##### ANSIBLE VERSION
```paste below
ansible [core 2.16.3]
  config file = /home/angelo/.ansible.cfg
  configured module search path = ['/home/angelo/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/angelo/.pyenv/versions/py312/lib/python3.12/site-packages/ansible
  ansible collection location = /home/angelo/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/angelo/.pyenv/versions/py312/bin/ansible
  python version = 3.12.2 (main, Feb 26 2024, 16:09:54) [GCC 9.4.0] (/home/angelo/.pyenv/versions/py312/bin/python3)
  jinja version = 3.1.3
  libyaml = True
```

##### COLLECTION VERSION

```
# /home/angelo/.pyenv/versions/py312/lib/python3.12/site-packages/ansible_collections
Collection                               Version
---------------------------------------- -------
amazon.aws                               7.2.0  
ansible.netcommon                        5.3.0  
ansible.posix                            1.5.4  
ansible.utils                            2.12.0 
ansible.windows                          2.2.0  
arista.eos                               6.2.2  
awx.awx                                  23.6.0 
azure.azcollection                       1.19.0 
check_point.mgmt                         5.2.2  
chocolatey.chocolatey                    1.5.1  
cisco.aci                                2.8.0  
cisco.asa                                4.0.3  
cisco.dnac                               6.10.2 
cisco.intersight                         2.0.7  
cisco.ios                                5.3.0  
cisco.iosxr                              6.1.1  
cisco.ise                                2.7.0  
cisco.meraki                             2.17.2 
cisco.mso                                2.5.0  
cisco.nxos                               5.3.0  
cisco.ucs                                1.10.0 
cloud.common                             2.1.4  
cloudscale_ch.cloud                      2.3.1  
community.aws                            7.1.0  
community.azure                          2.0.0  
community.ciscosmb                       1.0.7  
community.crypto                         2.17.1 
community.digitalocean                   1.26.0 
community.dns                            2.8.0  
community.docker                         3.7.0  
community.general                        8.3.0  
community.grafana                        1.7.0  
community.hashi_vault                    6.1.0  
community.hrobot                         1.9.0  
community.library_inventory_filtering_v1 1.0.0  
community.libvirt                        1.3.0  
community.mongodb                        1.6.3  
community.mysql                          3.8.0  
community.network                        5.0.2  
community.okd                            2.3.0  
community.postgresql                     3.3.0  
community.proxysql                       1.5.1  
community.rabbitmq                       1.2.3  
community.routeros                       2.12.0 
community.sap                            2.0.0  
community.sap_libs                       1.4.2  
community.sops                           1.6.7  
community.vmware                         4.1.0  
community.windows                        2.1.0  
community.zabbix                         2.3.1  
containers.podman                        1.11.0 
cyberark.conjur                          1.2.2  
cyberark.pas                             1.0.25 
dellemc.enterprise_sonic                 2.4.0  
dellemc.openmanage                       8.7.0  
dellemc.powerflex                        2.1.0  
dellemc.unity                            1.7.1  
f5networks.f5_modules                    1.27.1 
fortinet.fortimanager                    2.3.1  
fortinet.fortios                         2.3.4  
frr.frr                                  2.0.2  
gluster.gluster                          1.0.2  
google.cloud                             1.3.0  
grafana.grafana                          2.2.4  
hetzner.hcloud                           2.4.1  
hpe.nimble                               1.1.4  
ibm.qradar                               2.1.0  
ibm.spectrum_virtualize                  2.0.0  
ibm.storage_virtualize                   2.2.0  
infinidat.infinibox                      1.3.12 
infoblox.nios_modules                    1.6.1  
inspur.ispim                             2.2.0  
inspur.sm                                2.3.0  
junipernetworks.junos                    5.3.1  
kubernetes.core                          2.4.0  
lowlydba.sqlserver                       2.2.2  
microsoft.ad                             1.4.1  
netapp.aws                               21.7.1 
netapp.azure                             21.10.1
netapp.cloudmanager                      21.22.1
netapp.elementsw                         21.7.0 
netapp.ontap                             22.9.0 
netapp.storagegrid                       21.11.1
netapp.um_info                           21.8.1 
netapp_eseries.santricity                1.4.0  
netbox.netbox                            3.16.0 
ngine_io.cloudstack                      2.3.0  
ngine_io.exoscale                        1.1.0  
openstack.cloud                          2.2.0  
openvswitch.openvswitch                  2.1.1  
ovirt.ovirt                              3.2.0  
purestorage.flasharray                   1.26.0 
purestorage.flashblade                   1.15.0 
purestorage.fusion                       1.6.0  
sensu.sensu_go                           1.14.0 
splunk.es                                2.1.2  
t_systems_mms.icinga_director            2.0.1  
telekom_mms.icinga_director              1.35.0 
theforeman.foreman                       3.15.0 
vmware.vmware_rest                       2.3.1  
vultr.cloud                              1.12.1 
vyos.vyos                                4.1.0  
wti.remote                               1.0.5  

```

##### CONFIGURATION
```
CONFIG_FILE() = /home/angelo/.ansible.cfg
DEFAULT_TIMEOUT(/home/angelo/.ansible.cfg) = 30
EDITOR(env: EDITOR) = nano
PAGER(env: PAGER) = less

```

##### OS / ENVIRONMENT
Ubuntu: 20.04
Python: 3.12.2 (pyenv)
Ansible: 2.16.3

##### STEPS TO REPRODUCE
```yaml

    - google.cloud.gcp_bigquery_table:
        name: 'bg_table_name'
        dataset: 'bg_dataset_name'
        clustering:
          - 'category'
          - 'group'
        time_partitioning:
          field: 'created_at'
          type: 'MONTH'
        table_reference:
          dataset_id: 'bg_dataset_id'
          project_id: 'project_id'
          table_id: 'bg_table_id'
        schema:
          fields:
            - name: "id"
              type: "INT64"
              mode: "REQUIRED"
            - name: "test_name"
              type: "STRING"
            - name: "category"
              type: "STRING"
            - name: "group"
              type: "STRING"
            - name: "created_at"
              type: "TIMESTAMP"
        state: present
        project: 'project'
        auth_kind: 'service_account'
        service_account_file: './key.json'


```

##### EXPECTED RESULTS
Playbook task creates bigquery table with clustering

##### ACTUAL RESULTS
Error is reported:

```paste below

fatal: [localhost]: FAILED! => {
  "changed": false, 
  "msg": "GCP returned error: 
  {'error': 
    {'code': 400, 
     'message': 'Invalid JSON payload received. Unknown name \"clustering\" at \\'table\\': Proto field is not repeating, cannot start list.', 
     'errors': [{'message': 'Invalid JSON payload received. Unknown name \"clustering\" at \\'table\\': Proto field is not repeating, cannot start list.', 'reason': 'invalid'}], 
     'status': 'INVALID_ARGUMENT', 
     'details': [{'@type': 'type.googleapis.com/google.rpc.BadRequest', 
     'fieldViolations': [{'field': 'table', 'description': 'Invalid JSON payload received. Unknown name \"clustering\" at \\'table\\': Proto field is not repeating, cannot start list.'}]}]}}", 
     "request": {"body": "{\"kind\": \"bigquery#table\", \"tableReference\": {\"datasetId\": \"bg_dataset_name\", \"projectId\": \"project_id\", \"tableId\": \"bg_table_name\"}, \"clustering\": [\"category\", \"group\"], \"name\": \"bg_table_id\", \"timePartitioning\": {\"field\": \"created_at\", \"type\": \"MONTH\"}, 
     \"schema\": {\"fields\": [.........]}}", "method": "POST", "url": "https://bigquery.googleapis.com/bigquery/v2/projects/project/datasets/bg_table_name/tables"}}

```
