### ISSUE TITLE
Can't power down a virtual machine.

### ISSUE THREAD

**Issue by HichamMourad** [ansible-collections/google.cloud#624]
##### SUMMARY

Using the following in a playbook to shut down a vm.  It returns an error that is related to gcloud command line.

    - name: Stop the desired GCP VM instance
      google.cloud.gcp_compute_instance:
        project: "{{ gcp_project }}"
        zone: "{{ gcp_zone }}"
        auth_kind: serviceaccount
        status: "TERMINATED"
        deletion_protection: false
      when: gcp_instance_info.resources[0].name == "{{ vm_name }}"

The ERROR:
"msg": "GCP returned error: {'error': {'code': 400, 'message': 'VM has a Local SSD attached but an undefined value for `discard-local-ssd`. If using gcloud, please add `--discard-local-ssd=false` or `--discard-local-ssd=true` to your command.', 'errors': [{'message': 'VM has a Local SSD attached but an undefined value for `discard-local-ssd`. If using gcloud, please add `--discard-local-ssd=false` or `--discard-local-ssd=true` to your command.', 'domain': 'global', 'reason': 'badRequest'}]}}",

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

Google Cloud certified collection for Ansible Automation Platform.

##### ANSIBLE VERSION

```paste below
Ansible Automation Platform 2.4 latest.
```

##### COLLECTION VERSION

```paste below
1.3.0
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

RHEL 9

##### STEPS TO REPRODUCE

Trigger the above code in an ansible playbook.

```yaml

---
- name: Shutdown a GCP vm instance by name
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Retrieve info for the GCP VM instances
      google.cloud.gcp_compute_instance_info:
        project: "{{ gcp_project }}"
        zone: "{{ gcp_zone }}"
        auth_kind: serviceaccount
      register: gcp_instance_info

    - name: Stop the desired GCP VM instance
      google.cloud.gcp_compute_instance:
        project: "{{ gcp_project }}"
        zone: "{{ gcp_zone }}"
        auth_kind: serviceaccount
        status: "TERMINATED"
        deletion_protection: false
      when: gcp_instance_info.resources[0].name == "{{ vm_name }}"

```

##### EXPECTED RESULTS

power off the virtual machine

##### ACTUAL RESULTS

ERROR MESSAGE
"msg": "GCP returned error: {'error': {'code': 400, 'message': 'VM has a Local SSD attached but an undefined value for `discard-local-ssd`. If using gcloud, please add `--discard-local-ssd=false` or `--discard-local-ssd=true` to your command.', 'errors': [{'message': 'VM has a Local SSD attached but an undefined value for `discard-local-ssd`. If using gcloud, please add `--discard-local-ssd=false` or `--discard-local-ssd=true` to your command.', 'domain': 'global', 'reason': 'badRequest'}]}}",

```paste below

```
