### ISSUE TITLE
gcp_compute_ssl_certificate.py module, Invalid value for field 'sslCertificate', Must be a match of regex '[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?|[1-9][0-9]{0,19}'

### ISSUE THREAD

**Issue by Keith-Nowosielski-SJSU** [ansible-collections/google.cloud#626]
##### SUMMARY

When using module gcp_compute_ssl_certificate, receiving error :Invalid value for field 'sslCertificate', Must be a match of regex '[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?|[1-9][0-9]{0,19}.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

gcp_compute_ssl_certificate

##### ANSIBLE VERSION

```paste below
ansible-core 2.15.0rc2 (using awx) 
```

##### COLLECTION VERSION

```paste below
1.3.0 (using awx) 
```

##### CONFIGURATION

```paste below
using awx. 
```

##### OS / ENVIRONMENT

awx. 

##### STEPS TO REPRODUCE

```yaml
- name: Upload SSL | GCP 
  hosts: localhost
  connection: local
  gather_facts: No
  become: No
  vars:
    cert_out: "{{ lookup('file', '/tmp/certbot/{{ cert_name }}/cert.pem') }}"
    key_out: "{{ lookup('file', '/tmp/certbot/{{ cert_name }}/privkey.pem') }}"

  tasks: 

    - name: format key
      set_fact: 
        key: "{{ key_out|split('\n')|join }}"

    - name: format cert 
      set_fact: 
        cert: "{{ cert_out|split('\n')|join|split('\"')|join }}"

    - name: create a SSL certificate | GCP
      google.cloud.gcp_compute_ssl_certificate:
        name: "{{ cert_name }}"
        description: "{{ gcp_ssl_desc }}"
        certificate: |-
          {{ cert }}
        private_key: |-
          {{ key }}
        project: "{{ project }}"
        auth_kind: serviceaccount
        service_account_file: "{{ lookup('env', 'GCP_SERVICE_ACCOUNT_FILE') }}"
        state: present
```

##### EXPECTED RESULTS

I expect the certificate object to be created in GCP Compute ssl-certificates. 

##### ACTUAL RESULTS

{
  "request": {
    "url": "https://compute.googleapis.com/compute/v1/projects/prj_name/global/sslCertificates/certificate.com,
    "body": null,
    "method": "GET"
  },
  "msg": "GCP returned error: {'error': {'code': 400, 'message': \"Invalid value for field 'sslCertificate': 'certificate.com'. Must be a match of regex '[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?|[1-9][0-9]{0,19}'\", 'errors': [{'message': \"Invalid value for field 'sslCertificate': 'certificate.com'. Must be a match of regex '[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?|[1-9][0-9]{0,19}'\", 'domain': 'global', 'reason': 'invalid'}]}}",
  "exception": "  File \"/tmp/ansible_google.cloud.gcp_compute_ssl_certificate_payload_m8ppwro8/ansible_google.cloud.gcp_compute_ssl_certificate_payload.zip/ansible_collections/google/cloud/plugins/module_utils/gcp_utils.py\", line 336, in raise_for_status\n    response.raise_for_status()\n  File \"/usr/local/lib/python3.9/site-packages/requests/models.py\", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\n",
  "invocation": {
    "module_args": {
      "name": "certificate.com",
      "description": "testing ansible cert automation",
      "certificate": "-----BEGIN CERTIFICATE-----MIIG5***CERT***INFO***REMOVED***==-----END CERTIFICATE-----",
      "private_key": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
      "project": "prj_name",
      "auth_kind": "serviceaccount",
      "service_account_file": "/runner/env/tmpoqnseo3m",
      "state": "present",
      "env_type": "tower",
      "service_account_email": null,
      "service_account_contents": null,
      "access_token": null,
      "scopes": [
        "https://www.googleapis.com/auth/compute"
      ]
    }
  },
  "ansible_facts": {
    "discovered_interpreter_python": "/usr/bin/python3"
  },
  "_ansible_no_log": false,
  "changed": false
}

```paste below

```
