### ISSUE TITLE
Unable set service file from variable ( fact )

### ISSUE THREAD

**Issue by volga629-1** [ansible-collections/google.cloud#630]
##### SUMMARY
Unable set service account key from variable ( fact ) 
Some quoting issue.
When I set path without fact with "" it  reading OK.

Example : 

```
        service_account_file: "{{ bucket_key }}"
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
google.cloud.gcp_storage_bucket:

##### ANSIBLE VERSION

```paste below
rpm -qa | grep ansible
ansible-core-2.16.5-1.fc39.noarch
```

##### COLLECTION VERSION

```paste below
ansible-galaxy collection list google.cloud

# /usr/share/ansible/collections/ansible_collections
Collection   Version
------------ -------
google.cloud 1.3.0
```

##### CONFIGURATION

```paste below
 - name: Create a gcp bucket
      become: true
      become_user: root
      google.cloud.gcp_storage_bucket:
        name: nl-vault-01
        project: networklab-storage
        auth_kind: serviceaccount
        storage_class: REGIONAL
        service_account_file: "{{ bucket_key }}"
        state: present
      register: bucket
```

##### OS / ENVIRONMENT

```
Linux pbx01 6.5.6-300.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Oct  6 19:57:21 UTC 2023 x86_64 GNU/Linux

```

##### STEPS TO REPRODUCE

1. Set key path as variable
2.  Run playbook

```yaml
 - name: Create a gcp bucket
      become: true
      become_user: root
      google.cloud.gcp_storage_bucket:
        name: nl-vault-01
        project: networklab-storage
        auth_kind: serviceaccount
        storage_class: REGIONAL
        service_account_file: "{{ bucket_key }}"
        state: present
      register: bucket
```

##### EXPECTED RESULTS

Expecting proper reply from GCP

##### ACTUAL RESULTS

```paste below
"msg": "Unable to read service_account_file at /home/temp-master/{'files': [{'path': '/etc/gcsfuse/auth.json', 'mode': '0644', 'isdir': False, 'ischr': False, 'isblk': False, 'isreg': True, 'isfifo': False, 'islnk': False, 'issock': False, 'uid': 0, 'gid': 0, 'size': 2376, 'inode': 17128826, 'dev': 64768, 'nlink': 1, 'atime': 1715361596.640047, 'mtime': 1715028005.1589835, 'ctime': 1715028005.1589835, 'gr_name': 'root', 'pw_name': 'root', 'wusr': True, 'rusr': True, 'xusr': False, 'wgrp': False, 'rgrp': True, 'xgrp': False, 'woth': False, 'roth': True, 'xoth': False, 'isuid': False, 'isgid': False}], 'changed': False, 'msg': 'All paths examined', 'matched': 1, 'examined': 2, 'skipped_paths': {}, 'failed': False}: No such file or directory"

```
