### ISSUE TITLE
Add display device as an option to gcp_compute_instance.py

### ISSUE THREAD

**Issue by richardurw** [ansible-collections/google.cloud#643]
##### ISSUE TYPE
- Can we add display device option in the gcp compute instance module?

##### COMPONENT NAME

gcp_compute_instance.py

##### ADDITIONAL INFORMATION

This feature would be useful in the GCP console to see if the system is coming online or not. It allows for screen capture.

```yaml

name: Create an Instance 
      google.cloud.gcp_compute_instance:
        state: present
        name: "{{ machine_name | lower }}"
        machine_type: "{{ machine_type }}"
        zone: "{{ zone }}"
        disks:
          - auto_delete: true
            boot: true
            source: "{{ disk }}"                          
        deletion_protection: "{{ deleteprotection }}"     

```
