### ISSUE TITLE
Ansible plugin gcp_compute skipping

### ISSUE THREAD

**Issue by Hraesvelg** [ansible-collections/google.cloud#650]
## Summary
When i try to use gcp_compute plugin, ansible skip always the plugin. No specific error... just it skip the plugin and then it can"t load gcp_compute.yml config and finaly my inventory is empty

## ISSUE TYPE
- Bug Report

## COMPONENT NAME
gcp_compute

## ANSIBLE VERSION

```paste below
$ ansible --version
ansible [core 2.17.3]
```

## OS / ENVIRONMENT
Ubuntu

##### STEPS TO REPRODUCE

```yaml
[defaults]
host_key_checking = False
inventory = gcp_compute.yml
interpreter_python = auto_silent

[inventory]
enable_plugins = host_list, script, auto, yaml, ini, toml, google.cloud.gcp_compute
```

```yaml
plugin: google.cloud.gcp_compute
zones: # populate inventory with instances in these regions
  - us-central1-a
projects:
  - my-project
service_account_file: ./service_account.json
auth_kind: serviceaccount
keyed_groups:
  # Create groups from GCE labels
  - key: labels
    prefix: label
  - key: zone
    prefix: zone
hostnames:
  - my_hostname
compose:
  ansible_host: networkInterfaces[0].accessConfigs[0].natIP
```

## EXPECTED RESULTS

He should found all inventory

##### ACTUAL RESULTS

```paste below
[WARNING]: Failed to load inventory plugin, skipping google.cloud.gcp_compute
```

**Comment by p3ck** [comment]
Hello,

I am looking into your issue and I want to confirm a setting in your inventory config:

```
hostnames:
  - my_hostname
```

The above setting will fail since it's not a valid hostnames option.

```
        hostnames:
          description: A list of options that describe the ordering for which
              hostnames should be assigned. Currently supported hostnames are
              'public_ip', 'private_ip', 'name' or 'labels.vm_name'.
          default: ['public_ip', 'private_ip', 'name']
          type: list
          elements: string
```

Can you confirm your settings and what you are trying to do?

Thanks!
