### ISSUE TITLE
Disable previous version when updating secret

### ISSUE THREAD

**Issue by gpongelli** [ansible-collections/google.cloud#660]
##### SUMMARY
When updating a secret, it could be possible to disable previous version.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
gcp_secret_manager

##### ADDITIONAL INFORMATION
Avoid being able to use previous secret's versions without destroying secret.

```yaml
- name: Add a new version of a secret disabling previous one
  google.cloud.gcp_secret_manager:
    name: secret_key
    value: updated super secret disabling previous
    state: present
    disable_previous_version: true
```
