### ISSUE TITLE
glcoud based authentication for ansible

### ISSUE THREAD

**Issue by renich** [ansible-collections/google.cloud#669]
##### SUMMARY
this collection should work using one's environment when one has authenticated using gcloud, as the following documentation states (for terraform):

https://cloud.google.com/docs/terraform/authentication#local_dev_environment

This, actually, works with Terraform/OpenTofu. 

It doesn't work with Ansible.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
google_service_account or google_auth

##### ADDITIONAL INFORMATION

```yaml
plugin: google.cloud.gcp_compute
projects: xpc-25
hostnames:
  - name
```

```bash
ansible -i hosts.gcp.yaml -m ansible.builtin.ping all
```

That should just work if `gcloud auth application-default login` was done beforehand.
