### ISSUE TITLE
Cannot create Google-managed SSL

### ISSUE THREAD

**Issue by prakasa1904** [ansible-collections/google.cloud#671]
##### SUMMARY

Create certificate API not support to create Google-managed SSL.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

gcp_compute_ssl_certificate

##### ADDITIONAL INFORMATION

Currently `gcp_compute_ssl_certificate` only support SSL creation using external key. Sadly,  cannot create SSL using feature Google-managed certificate. I suggest to add 2 new variables:
- managed (dict)
- type: (str)

And remove required attribute from 2 parameters:
- certificate
- privateKey

based on Google Cloud Platform Document: https://cloud.google.com/compute/docs/reference/rest/v1/sslCertificates/insert

Implementation https://github.com/ansible-collections/google.cloud/pull/672

```yaml
---
- name: Create a Google-managed SSL Certificate
  google.cloud.gcp_compute_ssl_certificate:
    name: "dpanel-terpusat-com"
    description: "cloud.terpusat.com Google-managed Certificate"
    type: "MANAGED"
    managed:
      domains:
      - cloud.terpusat.com
    project: "terpusat-dpanel"
    auth_kind: "serviceaccount"
    service_account_file: "./credential.json"
    state: present
```
