### ISSUE TITLE
Unable to Add Multiple SSL Certificates to gcp_compute_target_https_proxy module

### ISSUE THREAD

**Issue by avbuben** [ansible-collections/google.cloud#673]
##### SUMMARY
The google.cloud.gcp_compute_target_https_proxy module fails to accept multiple SSL certificates when updating a target HTTPS proxy. The ssl_certificates parameter, which is documented to accept a list of strings, results in an error when provided with a list.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
google.cloud.gcp_compute_target_https_proxy

##### ANSIBLE VERSION

```paste below
ansible [core 2.18.2]
  config file = /home/artur/Documents/acm-autoupdates/ansible.cfg
  configured module search path = ['/home/artur/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/artur/venvs/ansible_2.18/lib/python3.12/site-packages/ansible
  ansible collection location = /home/artur/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/artur/venvs/ansible_2.18/bin/ansible
  python version = 3.12.3 (main, Feb  4 2025, 14:48:35) [GCC 13.3.0] (/home/artur/venvs/ansible_2.18/bin/python3)
  jinja version = 3.1.5
  libyaml = True

```

##### COLLECTION VERSION

```paste below
Collection   Version
------------ -------
google.cloud 1.5.1  
```

##### STEPS TO REPRODUCE
1. Define a list of SSL certificates:
```yaml
ssl_certs:
  - "projects/my-project/global/sslCertificates/certificate-1"
  - "projects/my-project/global/sslCertificates/certificate-2"
```
2. Use the google.cloud.gcp_compute_target_https_proxy module to update a target HTTPS proxy:
```yaml
- name: Update target HTTPS proxy
  google.cloud.gcp_compute_target_https_proxy:
    name: "{{ proxy_name }}"
    project: "{{ gcp_project }}"
    auth_kind: serviceaccount
    service_account_contents: "{{ gcp_service_account_contents }}"
    url_map:
      selfLink: "{{ url_map }}"
    ssl_certificates: "{{ ssl_certs }}"
    state: present
```

##### EXPECTED RESULTS
The module should accept the list of SSL certificates and successfully update the target HTTPS proxy with the specified certificates.

##### ACTUAL RESULTS
The module fails with the following error:

```paste below
TASK [Update target HTTPS proxy] ******************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Elements value for option 'ssl_certificates' is of type <class 'str'> and we were unable to convert to dict: dictionary requested, could not parse JSON or key=value"}
```
